name: Minimal Reusable

on:
  workflow_call:
    inputs:
      test_input:
        type: string
        required: false
        default: world

permissions:
  contents: read

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello ${{ inputs.test_input }}"
